language: c

sudo: false

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

env:
  matrix:
   - CONF="shared"
   - CONF="static"
   - CONF="shared-poll"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - clang

branches:
  only:
    - master

install:
  - if [[ $CONF == "shared" ]]; then ./autogen.sh && ./configure && make; fi
  - if [[ $CONF == "static" ]]; then ./autogen.sh && ./configure --disable-shared && make; fi
  - if [[ $CONF == "shared-poll" ]]; then ./autogen.sh && ./configure CFLAGS=-DDILL_POLL && make; fi

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
